interfaces:
  enp1s0f0:
    pvid: 1
  enp1s0f1:
    pvid: 1
    tagged_vlans: [1]
  enp3s0f0:
    pvid: 1
  enp3s0f1:
      pvid: 2

attacks:
  - name: ArpCachePoison
  - name: VlanHopping
  - name: DHCPStarvation
  - name: DHCPServer
  - name: STProot
