interfaces:
  enp1s0f0:
    pvid: 1
  enp1s0f1:
    pvid: 1
    tagged_vlans: [1]
  enp3s0f0:
    pvid: 1
  enp3s0f1:
      pvid: 2

attacks:
  - name: ArpCachePoison
  - name: VlanHopping
    victim_ip: '192.168.3.4'
    native_vlan: 1
    victim_vlan: 2
  - name: DHCPStarvation
  - name: DHCPServer
  - name: STProot
