interfaces:
  enp1s0f0:
    pvid: 1
  enp1s0f1:
    pvid: 1
    tagged_vlans: [1]
  enp3s0f0:
    pvid: 1
  enp3s0f1:
      pvid: 2

dhcp: True
ip4network: '192.168.3.0/24'
verbosity: 0

attacks:
  - name: ArpCachePoison
    module: ArpCachePoison
  - name: VlanHopping1
    module: VlanHopping
    victim_ip: '192.168.3.4'
    native_vlan: 1
    victim_vlan: 2
  - name: VlanHopping0
    module: VlanHopping
    victim_ip: '192.168.3.4'
    native_vlan: 0
    victim_vlan: 2
  - name: DHCPStarvationMAC
    module: DHCPStarvation
    identifier: mac
  - name: DHCPStarvationClientID
    module: DHCPStarvation
    identifier: clientID
  - name: DHCPServer
    module: DHCPServer
  - name: NDNASpoofing
    module: NDNASpoofing
  - name: STProot
    module: STProot
